server:
  port: 8082
spring:
  liquibase:
    change-log: "classpath:db/changelog/vine-changelog.xml"

  datasource:
    url: jdbc:h2:mem:wine_db
    username: sa
    password: password
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect

  h2:
    console.enabled: true

    show-sql: true
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    org:
      hibernate:
        sql: debug
        type:
          descriptor:
            sql:
              BasicBinder: trace